name: Pylint and Pytest


on:
    workflow_dispatch:
    push:
    pull_request:
        branches: [main]

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: echo to terminal
        run: |
            echo Commencing Testing start-up


  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd pipeline
          pip install -r requirements.txt

      - name: Run the unit tests with pytest
        id: test-app
        run: |
          cd pipeline
          pytest 
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd pipeline
          pip install -r requirements.txt

      - name: Run pylint
        id: pylint-pipeline
        run: |
          pylint --fail-under=8 pipeline/*.py